name: Laravel Dusk

on:
  push:
    branches: [ 2.0 ]
  pull_request:
    branches: [ 2.0 ]

jobs:
  dusk:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - laravel: '11.*'
            php: '8.2'
          - laravel: '12.*'
            php: '8.2'
          - laravel: '13.*'
            php: '8.3'

    name: Laravel ${{ matrix.laravel }}

    steps:
      - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
        with:
          php-version: ${{ matrix.php }}

      - uses: actions/checkout@v4

      - name: Composer Update
        run: composer self-update --2

      - name: Configure Composer for Dusk installs
        run: sh ./tests/bin/composer-ci-setup.sh

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: 8.0
          mysql root password: 123456
          mysql database: laravel
          mysql user: root
          mysql password: 123456

      - name: Install Dependencies
        run: |
          composer create-project --prefer-dist laravel/laravel laravel-tests "${{ matrix.laravel }}"
          sh ./tests/bin/install-dep.sh

      - name: Install Admin
        run: sh ./tests/bin/install-admin.sh

      - name: Start application server
        run: sh ./tests/bin/start.sh

      - name: Run test suite
        working-directory: laravel-tests
        env:
          APP_URL: http://127.0.0.1:8300
        run: php artisan dusk
